### ISSUE TITLE
URL design: user

### ISSUE THREAD

**Issue by dappledaily** [0xnan-dev/depub.space#18]
is it possible to change

https://depub.space/users/?account=cosmos1jwjsnrypjhen3qs6jgg74pmf7d6a32kl78j5hu

to

https://depub.space/users/cosmos1jwjsnrypjhen3qs6jgg74pmf7d6a32kl78j5hu

**Comment by 0xtaipoian** [comment]
it is impossible to do with static file website, coz it would lookup the folder called `cosmos1jwjsnrypjhen3qs6jgg74pmf7d6a32kl78j5hu` in users folder, what we can do it ether use hash params `#[address]` or  query string `?[address]`

**Comment by dappledaily** [comment]
what about them?

[https://d.mirror.xyz/FLqkPA3iN4x-p97UhfhWwaCx8rBmVo-1yttY20oaob4](https://d.mirror.xyz/FLqkPA3iN4x-p97UhfhWwaCx8rBmVo-1yttY20oaob4)

[https://mirror.xyz/0x4247c65610972d04Ca221bcc64Ff35F50c26E0F6](https://mirror.xyz/0x4247c65610972d04Ca221bcc64Ff35F50c26E0F6)

**Comment by makoto-jako** [comment]
It may work if the static hosting supports, for example:

https://vercel.com/support/articles/does-vercel-support-permanent-redirects

**Comment by makoto-jako** [comment]
More details if we're using vercel, which supports regex on the path matching

https://vercel.com/docs/cli#project-configuration/redirects

Example from the doc:

```json
{
  "redirects": [
    { "source": "/me", "destination": "/profile.html" },
    { "source": "/user", "destination": "/api/user", "permanent": false },
    { "source": "/view-source", "destination": "https://github.com/vercel/vercel" },
    {
      "source": "/:path((?!uk/).*)",
      "has": [
        {
          "type": "header",
          "key": "x-vercel-ip-country",
          "value": "GB"
        }
      ],
      "destination": "/uk/:path*",
      "permanent": false
    }
  ]
}
```

**Comment by 0xtaipoian** [comment]
NextJS used SSR / ISR to dynamically generate the static page with lambda on the fly, in our case we used IPFS, which a static file hosting.

**Comment by 0xtaipoian** [comment]
Another solution is host a lambda function for ISR and that continuously generate new user pages if the page doesn't exit, not sure is it feasible.

some reference: https://community.infura.io/t/nextjs-deploy-on-ipfs/1960/2

**Comment by 0xtaipoian** [comment]
Found a easier solution, use Cloudflare's URL rewrite rule, will try later
