### ISSUE TITLE
From Keplr to Wallet Connect

### ISSUE THREAD

**Issue by daisymarisfung** [0xnan-dev/depub.space#33]
I used to run it on Keplr. After I tried Wallet Connect, I cleared the cookie or remove Keplr connection and added it again. However, I am not able to use Keplr to connect to depub.SPACE again. It says, "No valid signer, please connect wallet"

**Comment by daisymarisfung** [comment]
And I know I can connect Keplr again and the write ISCN prompt pop-up, however, it says, "Failed to post your message, please try it again later."

**Comment by 0xtaipoian** [comment]
did you see Liker Land app ask for approve while posting message?

**Comment by daisymarisfung** [comment]
When I check the BigDipper, it says "failed to execute message; message index: 0: 0nanoekil is smaller than 1000000000nanoekil: insufficient funds" and it didn't go through when posting picture.

**Comment by 0xtaipoian** [comment]
Would you mind give me your wallet address?

**Comment by 0xtaipoian** [comment]
@daisymarisfung the 0nanoekil has been fixed, please test it again, Thanks!

**Comment by daisymarisfung** [comment]
It works now!!!!! Thanks~~
