### ISSUE TITLE
failed to post image

### ISSUE THREAD

**Issue by ckxpress** [0xnan-dev/depub.space#35]
Tried to tweet this:
![appledaily-20210615](https://user-images.githubusercontent.com/7088918/152085465-8244648e-fa03-4529-bc5d-391ea49a561f.png)

Signed with message of this ipfs hash: {"ipfs":"QmfXV8wzBxGDg7rebChq12XHS3qaQ1TJ2uXtF9Su7orWNm"

and got this

<img width="788" alt="Screenshot 2022-02-02 at 10 44 56 AM" src="https://user-images.githubusercontent.com/7088918/152085455-a5244c3c-265f-48ce-a43c-843549bb7521.png">
}

transaction (using NANOEKIL!?)
https://likecoin.bigdipper.live/transactions/3F18A2F7F52788A256D6AA71829EBA5F15824E81855B50B1066BFEAB8D6D58A0

**Comment by 0xtaipoian** [comment]
the env variable `COSMOS_DENOM` on Feek was assigned nanoekil, fixed, please test again

**Comment by ckxpress** [comment]
managed to get through the first transaction: https://likecoin.bigdipper.live/transactions/186DAE22DB0346136D5BFD424709BB58FF2C806226834F4FCDF59D7746E4421C

signed another transaction, and get the same "Failed to post your message, please try again later."

**Comment by ckxpress** [comment]
successfully posted. is the image actually stored on Arweave? saw the hash in ISCN but couldn't read it from arweave.net, i'm not so sure

**Comment by 0xtaipoian** [comment]
Can see my uploaded image on Arweave: https://ii6c557wiszkdoo45biyle3h3ci6ho4dzlti42a37jth3j5z3ddq.arweave.net/Qjwu9_ZEsqG53OhRhZNn2JHju4PK5o5oG_pmfae52Mc
