### ISSUE TITLE
new tweets not appearing in personal page

### ISSUE THREAD

**Issue by ckxpress** [0xnan-dev/depub.space#42]
[https://depub.space/users/?account=cosmos1w6es6du93xmhms60gwwtczr2p2h4cdm8sz26vj](https://depub.space/users/?account=cosmos1w6es6du93xmhms60gwwtczr2p2h4cdm8sz26vj)

**Comment by 0xtaipoian** [comment]
It shows after hard-refresh(CMD + Shift + R) which mean the result got cached before, will try to fix the cache mechanism while having new post
